<a href="https://colab.research.google.com/github/Ashagire-Adinew/-datasciencecoursera/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [3]:
!pip install simpletransformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 249 kB 5.1 MB/s 
     |████████████████████████████████| 43 kB 2.3 MB/s 
     |████████████████████████████████| 1.8 MB 62.2 MB/s 
     |████████████████████████████████| 1.2 MB 48.2 MB/s 
     |████████████████████████████████| 9.1 MB 42.5 MB/s 
     |████████████████████████████████| 4.4 MB 38.6 MB/s 
     |████████████████████████████████| 6.6 MB 49.3 MB/s 
     |████████████████████████████████| 362 kB 75.8 MB/s 
     |████████████████████████████████| 596 kB 67.9 MB/s 
     |████████████████████████████████| 101 kB 11.3 MB/s 
     |████████████████████████████████| 181 kB 60.2 MB/s 
     |████████████████████████████████| 145 kB 42.6 MB/s 
     |████████████████████████████████| 63 kB 982 kB/s 
     |████████████████████████████████| 212 kB 59.0 MB/s 
     |████████████████████████████████| 1.1 MB 60.7 MB/s 
     |██████████████████████████████

In [2]:
from google.colab import drive
drive=drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#from simpletransformers.langauge_representation import RepresentationModel
from simpletransformers.language_representation import RepresentationModel
sente=['Machine learning and deep learning are the part of AI','Data science will excel in future']
model=RepresentationModel(
	model_type='bert',
	model_name='bert_base_uncased',
	use_cuda=True)
word_vector=model.encode_sentences(sentence,combine_strategy=None)

print(word_vector.shape)
#sentence embdding
sent_vector=model.encode_sentences(sentence,combine_strategy=None)

print(sent_vector.shape)

OSError: ignored

In [4]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

# integer encode the documents
vocab_size = 100
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 3 #you must use you  sentence length size to get best accuracy
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 4, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', 
	loss='binary_crossentropy', 
	metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[59, 13], [82, 77], [75, 18], [47, 77], [36], [63], [25, 18], [70, 82], [25, 77], [74, 79, 13, 74]]
[[59 13  0]
 [82 77  0]
 [75 18  0]
 [47 77  0]
 [36  0  0]
 [63  0  0]
 [25 18  0]
 [70 82  0]
 [25 77  0]
 [79 13 74]]
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              400       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 413
Trainable params: 413
Non-trainable params: 0
_________________________________________________________________


2022-07-06 09:56:09.395537: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


None
Accuracy: 89.999998
